# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
           
        - uses: actions/checkout@v2
      
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5
        
        - name: Setup VSTest
          uses: darenm/Setup-VSTest@v1

        - name: Navigate to Workspace
          run: cd $GITHUB_WORKSPACE

        - name: Create Build Directory
          run: mkdir _build

        - name: Restore Packages
          run: nuget restore ThreadedProjectWorkshop1.sln

        - name: Build Solution
          run: |
            msbuild.exe ThreadedProjectWorkshop1.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl=../_build
        
        - name: Build with dotnet
          run: msbuild.exe  ThreadedProjectWorkshop1\ThreadedProjectWorkshop1.csproj 
        - name: Create the package
          run: dotnet pack --configuration Release ThreadedProjectWorkshop1\ThreadedProjectWorkshop1.csproj
        - name: Publish the package to GPR
          run: dotnet nuget push ThreadedProjectWorkshop1\ThreadedProjectWorkshop1.csproj/bin/Release/*.nupkg
        
        - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            name: ThreadedProjectWorkshop1
            path: ../_build/ThreadedProjectWorkshop1.csproj
